### ISSUE TITLE
Container fails to restart

### ISSUE THREAD

**Issue by AdamJLemmon** [stephen-fox/chrome-docker#1] opened 2017-11-07 22:09 UTC
I am able to boot the container and run chrome perfectly fine!

However if I stop the container and then start it again the container stays up for about 5 seconds that exits.

I have not been able to dig in to see logging output yet.

```docker run -p 5900:5900 -e VNC_SERVER_PASSWORD=password --name=chrome --user apps --privileged chrome-imi```

```docker stop chrome```

```docker start chrome```

Comes up and exits within ~5s.  And same behaviour is present with restart.  Thanks

**Comment by stephen-fox** [comment] 2017-11-12 18:05
Hi Adam,

Thank you for the report. I was able to reproduce the issue, and I have committed a fix for it to master. The underlying bug was that when a user VNCs into the container, and then stops the container while the VNC session is active, the xvfb lock file was left behind. The next time the container was started, xvfb would refuse to start because the lock file was still there.

The code changes can be found in pull request #2.

**Closed as completed** 2017-11-18 14:05 UTC
